#!mast .ruby bin lib man qed test [A-Z]*.*
.ruby
lib/detroit-rdoc.rb
lib/detroit-ri.rb
man/detroit-rdoc.5
man/detroit-rdoc.5.html
man/detroit-rdoc.5.ronn
man/detroit-ri.5
man/detroit-ri.5.html
man/detroit-ri.5.ronn
LICENSE.txt
README.rdoc
COPYING.rdoc
